apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: sonvt8/client
      context: client #working directory
      sync:
        manual:
          - src: src/**/*.js #copy changes to direct working pod, if it not match things in src directory, skaffold will update image
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sonvt8/comments
      context: comments
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sonvt8/event-bus
      context: event-bus
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sonvt8/moderation
      context: moderation
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sonvt8/posts
      context: posts
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sonvt8/query
      context: query
      sync:
        manual:
          - src: '*.js'
            dest: .
      docker:
        dockerfile: Dockerfile